---
- name: Add ananace-charts helm repository
  kubernetes.core.helm_repository:
    name: ananace-charts
    repo_url: "https://ananace.gitlab.io/charts"

- name: install matrix-synapse helm chart
  kubernetes.core.helm:
    name: matrix-synapse
    chart_ref: ananace-charts/matrix-synapse
    release_namespace: matrix
    create_namespace: true
    release_values:
      serverName: "matrix.{{ domain_name }}"
      config:
        enableRegistration: true
      ingress:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        tls:
          - hosts :
            - "matrix.{{ domain_name }}"
            secretName: "matrix-tls-secret"
      wellknown.enabled: true
      extraConfig:
        enable_registration_without_verification: true
    update_repo_cache: yes