---
- name: Add ananace-charts helm repository
  kubernetes.core.helm_repository:
    name: ananace-charts
    repo_url: "https://ananace.gitlab.io/charts"

- name: install matrix-synapse helm chart
  kubernetes.core.helm:
    name: matrix-synapse
    chart_ref: ananace-charts/matrix-synapse
    release_namespace: matrix
    create_namespace: true
    release_values:
      serverName: eimis.incubateur.net
#      config:
#        publicBaseurl: http://141.95.163.184:8008
      ingress:
        className: nginx
      wellknown.enabled: true
    update_repo_cache: yes