---
- name: Create a postgres database for keycloak
  kubernetes.core.k8s:
    state: present
    template: 'keycloak-db.yml.j2'
- name: Create a keycloak specific ingress
  kubernetes.core.k8s:
    state: present
    template: 'ingress.yml.j2'
- name: Wait for the keycloak ingress and its secrets to be ready and retrieve the information of the created secret
  shell: kubectl get secrets -n keycloak keycloak-tls-secret -o jsonpath="{$.data}"
  register: pod_info
  until: pod_info.stdout.find("tls.scrt") != -1
  retries: 30
  delay: 2
- name: Create a keycloak instance
  kubernetes.core.k8s:
    state: present
    template: 'keycloak.yml.j2'
- name: Import the psc realm into keycloak
  kubernetes.core.k8s:
    state: present
    template: 'keycloak-realm.yml'