---
- name: Create a postgres db for keycloak from a local file
  kubernetes.core.k8s:
    state: present
    template: 'keycloak-db.yml'
- name: Create a keycloak instance from a local file
  kubernetes.core.k8s:
    state: present
    template: 'keycloak.yml.j2'
- name: Create a keycloak specific ingress from a local file
  kubernetes.core.k8s:
    state: present
    template: 'ingress.yml.j2'