spec:
  template:
    spec:
      containers:
        - name: synapse
          volumeMounts:
            - name: msteams-registration
              mountPath: /data/
      volumes:
        - configMap:
            name: msteams-registration-configmap
          name: msteams-registration
          items:
            - key: "msteams-registration.yaml"
              path: "msteams-registration.yaml"
